robot:
  # Publish all joint states --------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1_motor1
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1_motor2
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1_motor3
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg2_motor1
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg2_motor2
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg2_motor3
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg3_motor1
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg3_motor2
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg3_motor3
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg4_motor1
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg4_motor2
    pid: {p: 50.0, i: 0.1, i: 1.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg4_motor3
    pid: {p: 50.0, i: 0.1, i: 1.0}
